// ─── Mock Data for Development ─────────────────────────────────
// Used when backend is not available. Gives the dashboard realistic data.

const NOW = new Date().toISOString();
const FIVE_MIN_AGO = new Date(Date.now() - 5 * 60 * 1000).toISOString();
const TEN_MIN_AGO = new Date(Date.now() - 10 * 60 * 1000).toISOString();
const THIRTY_MIN_AGO = new Date(Date.now() - 30 * 60 * 1000).toISOString();
const ONE_HOUR_AGO = new Date(Date.now() - 60 * 60 * 1000).toISOString();
const TWO_HOURS_AGO = new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString();

export const MOCK_WORKFLOWS = {
  executions: [
    {
      id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
      workflow_name: 'order-fulfillment',
      state: 'RUNNING',
      input_payload: { order_id: 'ORD-001', customer_id: 'CUST-042', total_value: 150, items: ['Widget A', 'Widget B'] },
      started_at: FIVE_MIN_AGO,
      completed_at: null,
    },
    {
      id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
      workflow_name: 'order-fulfillment',
      state: 'PAUSED',
      input_payload: { order_id: 'ORD-002', customer_id: 'CUST-099', total_value: 1200, items: ['Premium Gadget'] },
      started_at: TEN_MIN_AGO,
      completed_at: null,
    },
    {
      id: 'c3d4e5f6-a7b8-9012-cdef-123456789012',
      workflow_name: 'order-fulfillment',
      state: 'COMPLETED',
      input_payload: { order_id: 'ORD-003', customer_id: 'CUST-017', total_value: 89.99, items: ['Basic Item'] },
      started_at: THIRTY_MIN_AGO,
      completed_at: TEN_MIN_AGO,
    },
    {
      id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
      workflow_name: 'order-fulfillment',
      state: 'FAILED',
      input_payload: { order_id: 'ORD-004', customer_id: 'CUST-055', total_value: 349, items: ['Fragile Item', 'Another Item'] },
      started_at: ONE_HOUR_AGO,
      completed_at: THIRTY_MIN_AGO,
    },
    {
      id: 'e5f6a7b8-c9d0-1234-efab-345678901234',
      workflow_name: 'order-fulfillment',
      state: 'COMPLETED',
      input_payload: { order_id: 'ORD-005', customer_id: 'CUST-003', total_value: 59.00, items: ['Small Widget'] },
      started_at: TWO_HOURS_AGO,
      completed_at: ONE_HOUR_AGO,
    },
    {
      id: 'f6a7b8c9-d0e1-2345-fabc-456789012345',
      workflow_name: 'order-fulfillment',
      state: 'RUNNING',
      input_payload: { order_id: 'ORD-006', customer_id: 'CUST-078', total_value: 750, items: ['Luxury Item'] },
      started_at: FIVE_MIN_AGO,
      completed_at: null,
    },
  ],
  total: 6,
};

export const MOCK_WORKFLOW_DETAIL = {
  id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  workflow_name: 'order-fulfillment',
  state: 'RUNNING',
  input_payload: { order_id: 'ORD-001', customer_id: 'CUST-042', total_value: 150, items: ['Widget A', 'Widget B'] },
  started_at: FIVE_MIN_AGO,
  completed_at: null,
  tasks: [
    {
      id: 'task-001',
      task_id: 'validate-order',
      type: 'http',
      service: 'order-service',
      state: 'COMPLETED',
      depends_on: [],
      input_payload: { order_id: 'ORD-001' },
      result_payload: { valid: true, message: 'Order validated successfully' },
      attempt_number: 1,
      dispatched_at: FIVE_MIN_AGO,
      completed_at: new Date(Date.now() - 4.5 * 60 * 1000).toISOString(),
      attempts: [{ number: 1, state: 'COMPLETED', started_at: FIVE_MIN_AGO, completed_at: new Date(Date.now() - 4.5 * 60 * 1000).toISOString() }],
    },
    {
      id: 'task-002',
      task_id: 'process-payment',
      type: 'http',
      service: 'payment-service',
      state: 'COMPLETED',
      depends_on: ['validate-order'],
      input_payload: { order_id: 'ORD-001', amount: 150 },
      result_payload: { transaction_id: 'TXN-9876', status: 'charged' },
      attempt_number: 1,
      dispatched_at: new Date(Date.now() - 4.5 * 60 * 1000).toISOString(),
      completed_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      attempts: [{ number: 1, state: 'COMPLETED', started_at: new Date(Date.now() - 4.5 * 60 * 1000).toISOString(), completed_at: new Date(Date.now() - 4 * 60 * 1000).toISOString() }],
    },
    {
      id: 'task-003',
      task_id: 'manual-approval',
      type: 'human',
      state: 'SKIPPED',
      depends_on: ['process-payment'],
      condition: '${input.total_value} > 500',
      input_payload: {},
      result_payload: null,
      attempt_number: 0,
      dispatched_at: null,
      completed_at: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
      attempts: [],
    },
    {
      id: 'task-004',
      task_id: 'check-inventory',
      type: 'http',
      service: 'inventory-service',
      state: 'IN_PROGRESS',
      depends_on: ['process-payment'],
      input_payload: { items: ['Widget A', 'Widget B'] },
      result_payload: null,
      attempt_number: 1,
      dispatched_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      completed_at: null,
      attempts: [{ number: 1, state: 'IN_PROGRESS', started_at: new Date(Date.now() - 3 * 60 * 1000).toISOString() }],
    },
    {
      id: 'task-005',
      task_id: 'reserve-stock',
      type: 'http',
      service: 'inventory-service',
      state: 'IN_PROGRESS',
      depends_on: ['process-payment'],
      input_payload: { items: ['Widget A', 'Widget B'], order_id: 'ORD-001' },
      result_payload: null,
      attempt_number: 1,
      dispatched_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
      completed_at: null,
      attempts: [{ number: 1, state: 'IN_PROGRESS', started_at: new Date(Date.now() - 3 * 60 * 1000).toISOString() }],
    },
    {
      id: 'task-006',
      task_id: 'ship-order',
      type: 'http',
      service: 'shipping-service',
      state: 'PENDING',
      depends_on: ['check-inventory', 'reserve-stock'],
      input_payload: null,
      result_payload: null,
      attempt_number: 0,
      dispatched_at: null,
      completed_at: null,
      attempts: [],
    },
    {
      id: 'task-007',
      task_id: 'send-confirmation',
      type: 'http',
      service: 'notification-service',
      state: 'PENDING',
      depends_on: ['ship-order'],
      input_payload: null,
      result_payload: null,
      attempt_number: 0,
      dispatched_at: null,
      completed_at: null,
      attempts: [],
    },
    {
      id: 'task-008',
      task_id: 'cancel-order',
      type: 'http',
      service: 'order-service',
      state: 'PENDING',
      depends_on: [],
      trigger: 'on_failure_of:process-payment',
      input_payload: null,
      result_payload: null,
      attempt_number: 0,
      dispatched_at: null,
      completed_at: null,
      attempts: [],
    },
  ],
};

export const MOCK_WORKFLOW_LOGS = {
  events: [
    { id: 'evt-001', event_type: 'WORKFLOW_STARTED', payload: { workflow: 'order-fulfillment', order_id: 'ORD-001' }, created_at: FIVE_MIN_AGO },
    { id: 'evt-002', event_type: 'TASK_STARTED', payload: { task_id: 'validate-order' }, created_at: FIVE_MIN_AGO },
    { id: 'evt-003', event_type: 'TASK_COMPLETED', payload: { task_id: 'validate-order', result: 'valid' }, created_at: new Date(Date.now() - 4.5 * 60 * 1000).toISOString() },
    { id: 'evt-004', event_type: 'TASK_STARTED', payload: { task_id: 'process-payment' }, created_at: new Date(Date.now() - 4.5 * 60 * 1000).toISOString() },
    { id: 'evt-005', event_type: 'TASK_COMPLETED', payload: { task_id: 'process-payment', transaction_id: 'TXN-9876' }, created_at: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
    { id: 'evt-006', event_type: 'TASK_SKIPPED', payload: { task_id: 'manual-approval', reason: 'Condition not met: total_value <= 500' }, created_at: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
    { id: 'evt-007', event_type: 'TASK_STARTED', payload: { task_id: 'check-inventory' }, created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString() },
    { id: 'evt-008', event_type: 'TASK_STARTED', payload: { task_id: 'reserve-stock' }, created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString() },
  ],
};

export const MOCK_HUMAN_TASKS = [
  {
    id: 'ht-001',
    task_execution_id: 'task-ext-100',
    workflow_execution_id: 'b2c3d4e5-f6a7-8901-bcde-f12345678901',
    workflow_name: 'order-fulfillment',
    task_id: 'manual-approval',
    assignee: 'ops-team',
    status: 'PENDING',
    order_value: 1200,
    order_id: 'ORD-002',
    created_at: TEN_MIN_AGO,
  },
  {
    id: 'ht-002',
    task_execution_id: 'task-ext-200',
    workflow_execution_id: 'f6a7b8c9-d0e1-2345-fabc-456789012345',
    workflow_name: 'order-fulfillment',
    task_id: 'manual-approval',
    assignee: 'finance-team',
    status: 'PENDING',
    order_value: 750,
    order_id: 'ORD-006',
    created_at: FIVE_MIN_AGO,
  },
];

// Failed workflow detail for demo
export const MOCK_FAILED_WORKFLOW = {
  id: 'd4e5f6a7-b8c9-0123-defa-234567890123',
  workflow_name: 'order-fulfillment',
  state: 'FAILED',
  input_payload: { order_id: 'ORD-004', customer_id: 'CUST-055', total_value: 349, items: ['Fragile Item', 'Another Item'] },
  started_at: ONE_HOUR_AGO,
  completed_at: THIRTY_MIN_AGO,
  tasks: [
    {
      id: 'task-f01', task_id: 'validate-order', type: 'http', service: 'order-service', state: 'COMPLETED', depends_on: [],
      input_payload: { order_id: 'ORD-004' }, result_payload: { valid: true }, attempt_number: 1,
      dispatched_at: ONE_HOUR_AGO, completed_at: new Date(Date.now() - 58 * 60 * 1000).toISOString(),
      attempts: [{ number: 1, state: 'COMPLETED', started_at: ONE_HOUR_AGO, completed_at: new Date(Date.now() - 58 * 60 * 1000).toISOString() }],
    },
    {
      id: 'task-f02', task_id: 'process-payment', type: 'http', service: 'payment-service', state: 'FAILED', depends_on: ['validate-order'],
      input_payload: { order_id: 'ORD-004', amount: 349 },
      result_payload: { error: 'Payment gateway timeout — card network unreachable' },
      error: 'Payment gateway timeout — card network unreachable',
      attempt_number: 3,
      dispatched_at: new Date(Date.now() - 58 * 60 * 1000).toISOString(),
      completed_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      attempts: [
        { number: 1, state: 'FAILED', started_at: new Date(Date.now() - 58 * 60 * 1000).toISOString(), completed_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(), error: 'Connection refused' },
        { number: 2, state: 'FAILED', started_at: new Date(Date.now() - 54 * 60 * 1000).toISOString(), completed_at: new Date(Date.now() - 50 * 60 * 1000).toISOString(), error: 'Timeout after 5000ms' },
        { number: 3, state: 'FAILED', started_at: new Date(Date.now() - 49 * 60 * 1000).toISOString(), completed_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(), error: 'Payment gateway timeout — card network unreachable' },
      ],
    },
    {
      id: 'task-f03', task_id: 'cancel-order', type: 'http', service: 'order-service', state: 'COMPLETED', depends_on: [],
      trigger: 'on_failure_of:process-payment',
      input_payload: { order_id: 'ORD-004' }, result_payload: { cancelled: true }, attempt_number: 1,
      dispatched_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(), completed_at: new Date(Date.now() - 44 * 60 * 1000).toISOString(),
      attempts: [{ number: 1, state: 'COMPLETED', started_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(), completed_at: new Date(Date.now() - 44 * 60 * 1000).toISOString() }],
    },
    { id: 'task-f04', task_id: 'manual-approval', type: 'human', state: 'CANCELLED', depends_on: ['process-payment'], input_payload: null, result_payload: null, attempt_number: 0, dispatched_at: null, completed_at: null, attempts: [] },
    { id: 'task-f05', task_id: 'check-inventory', type: 'http', state: 'CANCELLED', depends_on: ['process-payment'], input_payload: null, result_payload: null, attempt_number: 0, dispatched_at: null, completed_at: null, attempts: [] },
    { id: 'task-f06', task_id: 'reserve-stock', type: 'http', state: 'CANCELLED', depends_on: ['process-payment'], input_payload: null, result_payload: null, attempt_number: 0, dispatched_at: null, completed_at: null, attempts: [] },
    { id: 'task-f07', task_id: 'ship-order', type: 'http', state: 'CANCELLED', depends_on: ['check-inventory', 'reserve-stock'], input_payload: null, result_payload: null, attempt_number: 0, dispatched_at: null, completed_at: null, attempts: [] },
    { id: 'task-f08', task_id: 'send-confirmation', type: 'http', state: 'CANCELLED', depends_on: ['ship-order'], input_payload: null, result_payload: null, attempt_number: 0, dispatched_at: null, completed_at: null, attempts: [] },
  ],
};
